### PR TITLE
fix: [Favorites-menu] When the volumn file not exist, gray the action

### PR DESCRIPTION
**Pull request by GongHeng2017**
as title

Log: fix issue#254
Issue: https://github.com/mhogomchungu/sirikali/issues/254

### CODE REVIEW

**Comment by GongHeng2017** [comment]
@mhogomchungu

**Comment by pzwahlen** [comment]
This seems to be a one-off check at launch time, which means it doesn't cope well with targets that may appear later (removable drives, remote CIFS shares). Would it make sense to periodically recheck the existence of the target ?

**Comment by mhogomchungu** [comment]
The favorites list is populated every time the favorites button is clicked so its state reflects the state of the system at the time the button is clicked.

**Comment by pzwahlen** [comment]
I am not sure we are talking about the same list.

I have enabled the option "show Favorite List On Context Menu" and therefore my question is about the right-click menu on the tray icon.

If this menu shows a disabled favorite for an external drive, that entry stays disabled even when pluging the drive. If I exit/relaunch SiriKali, then the entry gets enabled in the context menu.

**Pull request merged**
