### PR TITLE
Debian patches

### PR DESCRIPTION
**Pull request by rapgro**
appdata, manpages, etc.
We'll include in Fedora as well. Please add files to upstream.

### CODE REVIEW

**Comment by mhogomchungu** [comment]
Why do you want the debian folder here and not where its maintained at: https://github.com/davesteele/sirikali

The debian maintainer requested a long time ago for me to remove the folder because it was classing with his folder and it was inconvenient to remove by folder and replaced it with his before building for debian( atleast this was my understanding of the request)

**Comment by rapgro** [comment]
There's a wish to have at least support for appdata also in the Fedora package, manpages would be nice to have, too. No idea about the other stuff.
https://bugzilla.redhat.com/show_bug.cgi?id=1428202#c20

**Comment by mhogomchungu** [comment]
unbundled lxqt_wallet is fully supported in SiriKali.

SiriKali already ships with man pages(```sirikali.1.gz``` and ```sirikali.pkexec.1.gz```)

I just made a commit that adds appdata file[1]

[1] https://github.com/mhogomchungu/sirikali/commit/ef54268108f0f04e5e1c8aaffd2bf4bdcca4d087

**Comment by mhogomchungu** [comment]
I am closing this one as i think everything useful to fedora is already present in the git version.

**Comment by rapgro** [comment]
Thanks for the fast response!

**Pull request closed without merging**
